# --------------------------------------------------
# Site settings
# --------------------------------------------------

title: Florida Buddhist Monastery, TVI
email: Tayzawbatha851@gmail.com
description: "A Theravāda Buddhist monastery and 501(c)(3) non-profit organization located in Geneva, Florida."
baseurl: "" # leave empty for root of domain
url: "https://floridabuddhistmonastery.org"

# Optional (SEO + clarity)
twitter_username: ""
github_username: ""
facebook_username: ""
website: "https://americanmonk.org"

# --------------------------------------------------
# Navigation menu
# --------------------------------------------------
# You can add this section directly (replaces `navigation: main`)




  
sass:
  sass_dir: assets/css
  style: compressed

# --------------------------------------------------
# Theme settings
# --------------------------------------------------
collections:
  news:
    output: true
    permalink: /news/:year/:month/:day/:title/


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false

# --------------------------------------------------
# Plugins and theme
# --------------------------------------------------

remote_theme: "mmistakes/minimal-mistakes"
#theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-feed
  - jekyll-sitemap       # ✅ helps SEO
  - jekyll-include-cache
  - jekyll-remote-theme

# --------------------------------------------------
# Exclusions
# --------------------------------------------------
# You can safely leave this commented or as-is

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
